"""Repository port (interface). Services depend on this, not on SQLite directly.

Phase 2 can provide an alternative implementation (e.g. Redis-backed sync) that
satisfies the same protocol.
"""

from __future__ import annotations

from typing import Protocol

from ..domain.models import (
    DailyChallenge,
    Profile,
    Quote,
    RaceKind,
    RaceRecord,
    RaceResult,
    ReplayPoint,
)

# A loaded ghost: its replay timeline, the WPM achieved, and the exact quote.
GhostData = tuple[list[ReplayPoint], float, Quote]


class Repository(Protocol):
    # profile
    def get_profile(self) -> Profile: ...
    def recompute_profile(self) -> Profile: ...
    def delete_implausible_races(self, max_wpm: float = 300.0) -> int: ...
    def wipe(self) -> None: ...

    # quotes
    def upsert_quote(self, quote: Quote) -> int: ...

    # races
    def save_race(
        self,
        *,
        result: RaceResult,
        quote: Quote,
        started_at: str,
        is_daily: bool = False,
    ) -> int: ...

    def list_history(self, limit: int = 20, offset: int = 0) -> list[RaceRecord]: ...
    def count_races(self) -> int: ...

    # per-key stats (typing coach)
    def get_key_stats(self) -> dict[str, tuple[int, int]]: ...
    def record_key_stats(self, key_stats: dict[str, tuple[int, int]], updated_at: str) -> None: ...
    def average_wpm_accuracy(self) -> tuple[float, float]: ...
    def best_by_mode(self, kind: RaceKind = ...) -> dict[int, float]: ...
    def best_quote_run(self) -> tuple[float, int] | None: ...
    def top_runs(
        self, mode_seconds: int, limit: int = 10, kind: RaceKind = ...
    ) -> list[RaceRecord]: ...
    def top_quote_runs(self, limit: int = 10) -> list[RaceRecord]: ...

    # ghosts (always completed, plausible, quote-mode runs — same text)
    def personal_best_replay(self) -> GhostData | None: ...
    def last_replay(self) -> GhostData | None: ...
    def random_replay(self) -> GhostData | None: ...
    def best_replay_for_quote(self, ext_id: str) -> GhostData | None: ...

    # daily
    def get_or_create_daily(self, day: str, quote: Quote) -> DailyChallenge: ...
    def daily_days_played(self) -> list[str]: ...
    def daily_leaderboard(self, day: str, limit: int = 20) -> list[RaceRecord]: ...
